### ISSUE TITLE
Checking for ocaml bytes module... configure: error: Not found.

### ISSUE THREAD

**Issue by alvassin** [savonet/liquidsoap-full#12]
Hello!

While installing liquidsoap i see following errors:

```
****** Configuring ocaml-cry

./configure --with-cry-dir=../ocaml-cry/src
configure: WARNING: unrecognized options: --with-cry-dir
...
checking for camlp4oof... no
checking for camlp4orf... no
checking for camlp4prof... no
checking for camlp4r... camlp4r
checking for camlp4rf... no
checking for ocamlfind... ocamlfind
checking for ocaml standard library path... /usr/lib/ocaml
checking for caml/threads.h... yes
checking for gcc option to produce PIC... -fPIC
checking for ocaml bytes module... configure: error: Not found.
```
What is that mystic bytes module? Can't find anything related in debian repos :(

**Comment by samoht** [comment]
you need ocamlfind > 1.5 to have the mystic bytes module I think.

**Comment by AlReem** [comment]
Has anyone managed to fix this issue?  I am stuck at this error on Ubuntu 14.04.  I tried the following and still have the same issue.

Installed Ocaml 4.02
Installed bytes module available at https://github.com/chambart/ocaml-bytes

**Comment by toots** [comment]
That's weird. 

Do you have logs of the install of `ocaml-bytes`?

Also, more generally, have you tried installing `liduisdsoap` via `opam`? This is our preferred and supported method of installation now. See: http://liquidsoap.fm/download.html

**Comment by AlReem** [comment]
Thanks toots.  I was simply trying to achieve [AAC+ support](https://wiki.sourcefabric.org/pages/viewpage.action?pageId=13632310) for my ubuntu server running airtime and got stuck on the error exactly as this thread.  Looking at the instructions for installing liquidsoap via opam, it seems to be pointing to the repo of liquidsoap rather than liquidsoap-full.  How would I go about adding the optional dependency of aacplus in opam?

**Comment by toots** [comment]
Excellent idea, will do.

2016-01-23 12:53 GMT-06:00 Abuzayd <notifications@github.com>:

**Comment by toots** [comment]
Okay, this should be fixed now. `fdkaac` package has been added to `opam` and as optional dep for `liquidsoap`. Closing this issue now, please re-open/fill a new one should you need it.
