### ISSUE TITLE
ocaml-xmlplaylist Clone Issue

### ISSUE THREAD

**Issue by S54B32** [savonet/liquidsoap-full#13]
Hi! I am compiling liquidsoap on a system. However, I am seeing an issue I have never seen before. I notice that toots appears to have updated ocaml-xmlplaylist repository this afternoon, but when using 2.6.5 and invoking using "git clone https://github.com/savonet/liquidsoap-full"

I get the following error:

Submodule path 'ocaml-xmlplaylist': checked out '2da06606d55cbe9ad94b8fa273840a626a50d2ae'
Cloning into 'website/savonet.github.io'...
The authenticity of host 'github.com (192.30.252.131)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.131' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:savonet/savonet.github.io.git' into submodule path 'website/savonet.github.io' failed
make: *** [init] Error 1

Thank you in advance for any advice :-)

**Comment by smimram** [comment]
Yes it seems that @toots latest changes to make the website upload work broke things. We get this on travis too: https://travis-ci.org/savonet/liquidsoap/builds/101095827

**Comment by S54B32** [comment]
Thanks for the reply, Samuel. I will await a fix and attempt to re-compile next week :+1:
