### ISSUE TITLE
Make Fails - 

### ISSUE THREAD

**Issue by S54B32** [savonet/liquidsoap-full#14]
Hello! I am wondering if anyone has any advice for me. I am attempting to compile Liquidsoap on an ARM system which I have done in the past with success. However, on this occasion I am receiving an error at the make stage.

I am running Debian Wheezy, and I have cloned liquidsoap-full. Make init, make update, bootstrap and configuring all appear to complete OK. But when I perform make I receive the following error:
```
OCAMLDEP
File "tools/avi.ml", line 48, characters 18-28:
Error: Integer literal exceeds the range of representable integers of type int
OCAMLOPT -c shutdown.ml
OCAMLOPT -c tools/stdlib.ml
OCAMLOPT -c tools/doc.ml
OCAMLOPT -c tools/utils.ml
OCAMLOPT -c tools/plug.ml
OCAMLOPT -c tools/dyntools.ml
OCAMLOPT -c tools/rqueue.ml
File "tools/rqueue.ml", line 1:
Error: Could not find the .cmi file for interface tools/rqueue.mli.
make[3]: *** [tools/rqueue.cmx] Error 2
make[3]: Leaving directory `/home/icecast/liquidsoap-full/liquidsoap/src'
make[2]: *** [all-auto-ocaml-prog] Error 2
make[2]: Leaving directory `/home/icecast/liquidsoap-full/liquidsoap/src'
make[1]: *** [all-subdirs] Error 2
make[1]: Leaving directory `/home/icecast/liquidsoap-full/liquidsoap'
make: *** [all] Error 1
```

[liquidsoap_bootstrap.txt](https://github.com/savonet/liquidsoap-full/files/87192/liquidsoap_bootstrap.txt)
[liquidsoap_configure.txt](https://github.com/savonet/liquidsoap-full/files/87194/liquidsoap_configure.txt)
[liquidsoap_make.txt](https://github.com/savonet/liquidsoap-full/files/87193/liquidsoap_make.txt)

My logs in full are attached. Does anyone have any ideas on this? Any advice is much appreciated.

**Comment by S54B32** [comment]
After trying to get this sorted, I manually run ocaml -c liquidsoap/src/tools/rqueue.mli then re-run make. Once I have done this I seem to have got past the rqueue.cli error but am now met with:
```
File "avi.ml", line 48, characters 18-28:
Error: Integer literal exceeds the range of representable integers of type int
```
This causes make to fail

**Comment by smimram** [comment]
Thanks for noticing this. We did not have it because we are on 64bits architectures and you are on 32bits. It should be fixed by https://github.com/savonet/liquidsoap/commit/d9d8fa569a5485dc1d8ba772c424611132785120.
