### ISSUE TITLE
AAC+ on ubuntu after installing liquidsoap-plugin-all

### ISSUE THREAD

**Issue by AlReem** [savonet/liquidsoap-full#20]
Thanks for the package `liquidsoap-plugin-all` for trusty.  It let me install all plugins in one shot.  Can you please advise me how I will be able to configure an aac+ encoder?  I saw another issue here in which it was recommended to use fdk-aac.  Does this mean that I should be recompiling liquidsoap via the opam route?

**Comment by toots** [comment]
Hi,

It should in theory be possible to activate the dynamic AAC+ encoder by compiling ocaml-aacplus and installing it on your system.

However, I'd recommend using `opam` to install liquidsoap. We actively maintain these packages and they should work fine on most linux and OSX systems.

**Comment by AlReem** [comment]
Thanks toots.  I have a related question.  I have done the compilation using opam and have the binaries.  I have a requirement to install it on multiple servers running the same OS.  Is there any way that I can transfer the binaries and libraries without installing opam, do you think it would work?  Sorry for asking this, I should have tried.  However, appreciate your feedback if I get stuck in trying this.

**Comment by toots** [comment]
This is not a easy thing to do but we have documented part of it here: http://liquidsoap.fm/doc-1.2.0/custom-path.html
