### ISSUE TITLE
Error on make init

### ISSUE THREAD

**Issue by JipeLie** [savonet/liquidsoap-full#24]
Hey,
When I try to run make init from the latest commit on the master branch, I get this error:

fatal: reference is not a tree: 1c3f5c0d8a03291a400212fb70a4a2c282f00e87
Unable to checkout '1c3f5c0d8a03291a400212fb70a4a2c282f00e87' in submodule path 'liquidsoap'
Makefile.git:6: recipe for target 'init' failed
make: *** [init] Error 1

Thank you

**Comment by toots** [comment]
Should be fixed now.

**Comment by JipeLie** [comment]
Thank it's work
