### ISSUE TITLE
./configure error

### ISSUE THREAD

**Issue by JipeLie** [savonet/liquidsoap-full#25]
Hey,

When i try a "./configure --enable-debugging --disable-graphics" i have this error

checking for gcc option to produce PIC... -fPIC
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking whether pkg-config knows about ao... configure: error: ao.pc not found.. Do you need to set PKG_CONFIG_PATH?

What i need to fix them ?

Thank you

**Comment by JipeLie** [comment]
No body have a idea about my error ?

**Comment by toots** [comment]
Yes, you are missing `libao`. I'd recommend to switch to `opam` which is the installation method recommended now. See: http://liquidsoap.fm/download.html Good luck!

**Comment by JipeLie** [comment]
Okay yes thank you i will try this way
