### ISSUE TITLE
Updates for release 1.3.0?

### ISSUE THREAD

**Issue by bburton** [savonet/liquidsoap-full#26]
It seems some of the packages listed in https://github.com/savonet/liquidsoap/blob/master/INSTALL are missing here in the PACKAGES.{default,minimal} files and as Git submodule references. At least four I found are inotify, ssl, magic and yojson.

**Comment by toots** [comment]
Hi,

The PACKAGES file only refer to packages that we maintain, which isn't the case for these guys.

Thanks for reporting, though!
