### ISSUE TITLE
Seems this repo is outdated

### ISSUE THREAD

**Issue by rrolla** [savonet/liquidsoap-full#32]
For example main liquidsoap bump was 8 months ago.

~~If I want the latest code I need recursively all submodules checkout to master and pull?~~

Okay i see that `make update` do that https://github.com/savonet/liquidsoap-full/blob/master/Makefile.git#L29

**Comment by smimram** [comment]
I've juste updated it but yes, `make update` is the way to go.

**Comment by rrolla** [comment]
Very nice :)
